spring.application.name=backend
# Configurações do Banco de Dados (PostgreSQL)
# Altere 'localhost:5432/limpac_db' para o nome do seu banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/limpac_db

spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
# 'update' cria as tabelas automaticamente (como a tabela 'calculos' e 'users')
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#  Formatação de JSON (para as datas ficarem legíveis nos DTOs)
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Sao_Paulo